// <auto-generated />
using System;
using CFMS.ShiftService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CFMS.ShiftService.Infrastructure.Migrations
{
    [DbContext(typeof(ShiftDbContext))]
    [Migration("20260403030856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CFMS.ShiftService.Core.Entities.ShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShiftConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WorkingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ShiftConfigId");

                    b.HasIndex("UserId", "WorkingDate");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("CFMS.ShiftService.Core.Entities.ShiftConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("FranchiseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RequiredStaffCount")
                        .HasColumnType("int");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ShiftConfigs");
                });

            modelBuilder.Entity("CFMS.ShiftService.Core.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("CFMS.ShiftService.Core.Entities.ShiftConfig", "ShiftConfig")
                        .WithMany("Assignments")
                        .HasForeignKey("ShiftConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftConfig");
                });

            modelBuilder.Entity("CFMS.ShiftService.Core.Entities.ShiftConfig", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
